// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizzardry.Data;

namespace Quizzardry.Migrations
{
    [DbContext(typeof(QuestionsDbContext))]
    partial class QuestionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quizzardry.Models.Questions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer1")
                        .IsRequired();

                    b.Property<string>("Answer2")
                        .IsRequired();

                    b.Property<string>("Answer3")
                        .IsRequired();

                    b.Property<string>("CorrectAnswer")
                        .IsRequired();

                    b.Property<string>("Question")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Questions");

                    b.HasData(
                        new { ID = 1, Answer1 = "Physicist Kenneth Bainbridge", Answer2 = "Actor Kenneth Branaugh", Answer3 = "Singer Kenneth \"Babyface\" Edmonds", CorrectAnswer = "Nobody!", Question = "In REM's \"What's the Frequency, Kenneth\" who is the titular Kenneth?" },
                        new { ID = 2, Answer1 = "Quad City DJs", Answer2 = "C + C Music Factory", Answer3 = "The Baha Men", CorrectAnswer = "Haddaway", Question = "The Euro-pop dance hit \"What is Love\" is probably still stuck in your head. Whose fault is that?" },
                        new { ID = 3, Answer1 = "The Ronnettes", Answer2 = "The Shirellas", Answer3 = "The Byrds", CorrectAnswer = "The Supremes", Question = "Covered by Phil Collins in 1982, what group released \"You Can't Hurry Love\" in 1966?" },
                        new { ID = 4, Answer1 = "Leonard Nemoy", Answer2 = "James Doohan", Answer3 = "DeForest Kelley", CorrectAnswer = "George Takei", Question = "Which Star Trek TOS cast member never appeared in an epsiode of Star Trek: TNG?" },
                        new { ID = 5, Answer1 = "The Space Needle", Answer2 = "The Statue of Liberty", Answer3 = "The Washington Monument", CorrectAnswer = "The Gateway Arch", Question = "Which of the following structures is the tallest?" },
                        new { ID = 6, Answer1 = "Pong", Answer2 = "Space Invaders", Answer3 = "Asteroids", CorrectAnswer = "Computer Space", Question = "What was the name of the first commercially released video game?" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
